name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      # Agrega este paso para configurar pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0  # ← Especifica la versión de pnpm
          
      - name: Install dependencies
        run: pnpm install  # ← Cambia npm por pnpm si usas pnpm
        
      - name: Build
        run: pnpm run build  # ← Cambia npm por pnpm
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
